export type Permission =
  | 'VIEW_PROVIDER_DASHBOARD' | 'VIEW_BOU_DASHBOARD' | 'SUBMIT_INTELLIGENCE'
  | 'VIEW_INTELLIGENCE' | 'PROPOSE_INDICATOR' | 'REVIEW_INDICATOR'
  | 'REVIEW_DISCLOSURE' | 'SCHEDULE_REPORT' | 'MANAGE_INSTITUTION_USERS'
  | 'MANAGE_ALL_USERS' | 'ASSIGN_PROVIDER_ROLE' | 'ASSIGN_BOU_ROLE'
  | 'MANAGE_API_KEYS' | 'ONBOARD_INSTITUTION' | 'VIEW_AUDIT'

