import type { UserRole } from './types'
import type { Permission } from './permissions'

export const ROLE_PERMISSIONS: Record<UserRole, readonly Permission[]> = {
  FRAUD_ANALYST: ['VIEW_PROVIDER_DASHBOARD', 'SUBMIT_INTELLIGENCE', 'VIEW_INTELLIGENCE', 'PROPOSE_INDICATOR'],
  FRAUD_SUPERVISOR: ['VIEW_PROVIDER_DASHBOARD', 'SUBMIT_INTELLIGENCE', 'VIEW_INTELLIGENCE', 'PROPOSE_INDICATOR', 'REVIEW_DISCLOSURE', 'SCHEDULE_REPORT'],
  INSTITUTION_ADMIN: ['VIEW_PROVIDER_DASHBOARD', 'MANAGE_INSTITUTION_USERS', 'ASSIGN_PROVIDER_ROLE', 'MANAGE_API_KEYS', 'SCHEDULE_REPORT'],
  COMPLIANCE_AUDITOR: ['VIEW_PROVIDER_DASHBOARD', 'VIEW_AUDIT', 'SCHEDULE_REPORT'],
  BOU_OVERSIGHT_OFFICER: ['VIEW_BOU_DASHBOARD', 'REVIEW_INDICATOR', 'VIEW_AUDIT', 'SCHEDULE_REPORT', 'ONBOARD_INSTITUTION'],
  BOU_ADMINISTRATOR: ['VIEW_BOU_DASHBOARD', 'REVIEW_INDICATOR', 'VIEW_AUDIT', 'SCHEDULE_REPORT', 'MANAGE_ALL_USERS', 'ASSIGN_PROVIDER_ROLE', 'ASSIGN_BOU_ROLE', 'MANAGE_API_KEYS', 'ONBOARD_INSTITUTION'],
}

export function roleHasPermission(role: UserRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role].includes(permission)
}

